name       : libwpe
version    : 1.2.1
release    : 1
source     :
    - https://github.com/WebPlatformForEmbedded/libwpe/releases/download/1.2.1/libwpe-1.2.1.tar.xz : 00e103c6fa226b0d979c29d14c9e8168c4bec7b0b5108f3705a037cda5609d7d
license    : BSD-2-Clause
component  : programming.library
summary    : General-purpose library specifically developed for the WPE-flavored port of WebKit.
description: |
    General-purpose library specifically developed for the WPE-flavored port of WebKit.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(xkbcommon)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
