name       : libwpe
version    : 1.10.0
release    : 6
source     :
    - https://github.com/WebPlatformForEmbedded/libwpe/releases/download/1.10.0/libwpe-1.10.0.tar.xz : 2415e270d45e3595ed4052bc105f733744dc2d3677e12ff4a831e5029841084d
license    : BSD-2-Clause
component  : programming.library
summary    : General-purpose library specifically developed for the WPE-flavored port of WebKit.
description: |
    General-purpose library specifically developed for the WPE-flavored port of WebKit.
builddeps  :
    - pkgconfig(gbm)
    - pkgconfig(x11)
    - pkgconfig(xkbcommon)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
