name       : libwpe
version    : 1.8.0
release    : 5
source     :
    - https://github.com/WebPlatformForEmbedded/libwpe/releases/download/1.8.0/libwpe-1.8.0.tar.xz : a6f00a7d091cbd4db57fe7ee3b4c12c6350921d654ed79812800a26c888481d2
license    : BSD-2-Clause
component  : programming.library
summary    : General-purpose library specifically developed for the WPE-flavored port of WebKit.
description: |
    General-purpose library specifically developed for the WPE-flavored port of WebKit.
builddeps  :
    - pkgconfig(gbm)
    - pkgconfig(x11)
    - pkgconfig(xkbcommon)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
