name       : libwpe
version    : 1.10.1
release    : 7
source     :
    - https://github.com/WebPlatformForEmbedded/libwpe/releases/download/1.10.1/libwpe-1.10.1.tar.xz : a327b3ffcf2356dbe8148c1db4bbdc5359d7e7163d177f67551a8393b144adf0
license    : BSD-2-Clause
component  : programming.library
summary    : General-purpose library specifically developed for the WPE-flavored port of WebKit.
description: |
    General-purpose library specifically developed for the WPE-flavored port of WebKit.
builddeps  :
    - pkgconfig(gbm)
    - pkgconfig(x11)
    - pkgconfig(xkbcommon)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
